name: Django CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
          
      - name: Check build status
        run: |
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Build succeeded"
          else
            echo "Build failed"
          fi
          exit $exit_code
